### ISSUE TITLE
As PM of Project Solda I would like to have all source code developed for the Bill of Material Dashboard published as Open Source

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/aliens4friends-dashboard#1]
Publish the source code of the Bill of Material Dashboard published as Open Source:
- [x] ask Martin to pull-request the source code develop <-- @mrabans
- [x] Project code needs cleanup and documentation (Martin said approx. 8th June) (blocked) <-- @mrabans
- [x] create a pipeline to build the dashboard on our infrastructure <-- @Piiit

**Comment by Piiit** [comment]
Waiting for PR --> blocked

**Comment by Piiit** [comment]
@mrabans Have you any news for this ticket?

I'll send you an invitation for this repo

**Comment by mrabans** [comment]
@Piiit Just made a pull request from the fork https://github.com/mrabans/aliens4friends-dashboard

**Comment by mrabans** [comment]
Here is another pull request with the latest changes: https://github.com/noi-techpark/aliens4friends-dashboard/pull/6
