### ISSUE TITLE
Hack in the vue.blade.php to use HTTPS only, needs to be fixed

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/aliens4friends-dashboard#8]
This was a fast hack to bring the dashboard online, we need to find a proper way to not have mixed content, which some browsers would block. For example, here the download of js/app.js is sometimes http://... and therefore blocked.

**Comment by Piiit** [comment]
@mrabans FYI

**Comment by mrabans** [comment]
right. Is this a todo or a fyi?

**Comment by Piiit** [comment]
@mrabans fyi for you and todo for Alex C, I guess :-)

**Comment by mrabans** [comment]
@Piiit Pipeline file https://github.com/noi-techpark/aliens4friends-dashboard/blob/main/infrastructure/jenkins/ci.groovy does a copy from the example file but I didn't find where the pipeline sets the correct APP_URL (with https) in the .env file? 
Could you please show me the right place?

**Comment by mrabans** [comment]
Fixed and replaced with a config to force HTTPS. Infos added to the readme.

**Comment by Piiit** [comment]
@mrabans Thanks for cleaning the issues here, but we need to keep this one open until we fix the deployment on our infrastructure. Otherwise I cannot test it... The workflow would be that you move it to To Review on your Kanban, and I close it afterwards... we need always to test things on our machines. Thanks
